### ISSUE TITLE
Get Request Filters by Field Name

### ISSUE THREAD

**Issue by dblane** [bergant/airtabler#2]
Is there currently a way to use a GET request with field criteria? Like in the example you provide, can  one select just hotels with 4 stars to be retrieved?

Here is the documentation that says it is possible.

> fields. array of strings. optional
> Only data for fields whose names are in this list will be included in the records. If you don't need every field, you can use this parameter to reduce the amount of data transferred.
[https://airtable.com/api/docs#curl/table:articles:list](url)

**Comment by syrnick** [comment]
See #1, You could add filterByFormula to https://github.com/bergant/airtabler/blob/master/R/airtabler.R#L86 and propagate it down to the GET request.

**Comment by bergant** [comment]
A brand new version of airtabler now supports the (not so) new airtable parameters (like filterByFormula, fields, sort ...). However, you have to use `select` function instead of `get` (see [readme](https://github.com/bergant/airtabler#airtabler) for usage examples). The old one (`get`) still works as in previous versions.

Like @syrnick already mentioned, the parameter `filterByFormula` can be used to filter the results. For example, `TravelBucketList$Hotels$select(filterByFormula = "(Stars = '****')")` will select only hotels with 4 stars.

**Comment by bergant** [comment]
Closed with 791327a
